parameters:
    twilio.class: Blackford\TwilioBundle\Service\TwilioWrapper
    twilio.capability.class: Blackford\TwilioBundle\Service\TwilioCapabilityWrapper
    twilio.lookups.class: Blackford\TwilioBundle\Service\TwilioLookupsWrapper

services:
    twilio.api:
        class: '%twilio.class%'
    twilio.capability:
        class: '%twilio.capability.class%'
    twilio.lookups:
        class: '%twilio.lookups.class%'
